# Generated by Django 3.0 on 2019-12-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadTaxista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nfuncionario', models.CharField(max_length=100)),
                ('Nempresa', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
            ],
        ),
    ]
