# Generated by Django 3.0 on 2019-12-12 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpTaxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100)),
                ('CNPJ', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='cadtaxista',
            old_name='numero',
            new_name='CNH_profissional',
        ),
        migrations.RemoveField(
            model_name='cadtaxista',
            name='descricao',
        ),
        migrations.AddField(
            model_name='cadtaxista',
            name='CPF',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadtaxista',
            name='RG',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadtaxista',
            name='cor_moto',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadtaxista',
            name='placa',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadtaxista',
            name='telefone',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadtaxista',
            name='Nempresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Taxi.EmpTaxi'),
        ),
    ]
