# Generated by Django 3.0 on 2019-12-12 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Taxi', '0002_auto_20191212_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadtaxista',
            name='email',
            field=models.EmailField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadtaxista',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
